from kedro.pipeline import Pipeline, node

from .nodes import (
    ICD_code_processing,
    baseline_n_cases,
    date_preprocessing,
    fraction_n_cases,
    missing_data_prepro,
    preprocess_wrong_class,
    preprocessing_by_sheets,
    smooth_n_cases,
    sum_same_week,
    translate_rename,
    upload_data,
)


def create_pipeline(**kwargs):
    return Pipeline(
        [
            node(
                preprocessing_by_sheets,
                inputs="HCL_ER_historical",
                outputs="extract_HCL_ER_historical",
                name="extract_HCL_ER_historical_node",
            ),
            node(
                date_preprocessing,
                inputs="extract_HCL_ER_historical",
                outputs="HCL_ER_historical_date_preprocessing",
                name="HCL_ER_historical_date_preprocessing_node",
            ),
            node(
                sum_same_week,
                inputs="HCL_ER_historical_date_preprocessing",
                outputs="HCL_ER_historical_sum_week",
                name="HCL_ER_historical_sum_week_node",
            ),
            node(
                translate_rename,
                inputs="HCL_ER_historical_sum_week",
                outputs="HCL_ER_historical_translate",
                name="HCL_ER_historical_translate_node",
            ),
            node(
                ICD_code_processing,
                inputs="HCL_ER_historical_translate",
                outputs="HCL_ER_historical_ICD_code",
                name="HCL_ER_historical_ICD_code_node",
            ),
            node(
                preprocess_wrong_class,
                inputs="HCL_ER_historical_ICD_code",
                outputs="HCL_ER_historical_preprocessing",
                name="HCL_ER_historical_preprocessing_node",
            ),
            node(
                missing_data_prepro,
                inputs="HCL_ER_historical_preprocessing",
                outputs="HCL_ER_historical_missing_data",
                name="HCL_ER_historical_missing_data_node",
            ),
            node(
                smooth_n_cases,
                inputs="HCL_ER_historical_missing_data",
                outputs="HCL_ER_historical_smooth",
                name="HCL_ER_historical_smooth_node",
            ),
            node(
                baseline_n_cases,
                inputs="HCL_ER_historical_smooth",
                outputs="HCL_ER_historical_baseline",
                name="HCL_ER_historical_baseline_node",
            ),
            node(
                fraction_n_cases,
                inputs="HCL_ER_historical_baseline",
                outputs="HCL_ER_final",
                name="HCL_ER_final_node",
            ),
            node(
                upload_data,
                inputs="HCL_ER_final",
                outputs="HCL_ER_final.local",
                name="HCL_ER_final_extract_node",
            ),
        ]
    )
