# src/data_project/pipeline.py
from kedro.pipeline import Pipeline, node

from .nodes import (
    dates_formatting,
    extract_columns,
    get_most_recent_dataframe,
    missing_data_prepro_I,
    missing_data_prepro_II,
    missing_data_prepro_III,
    smooth_n_cases,
    smooth_n_critical,
    smooth_n_death,
    table_I_baseline_creation,
    table_I_calculation_nowcasting,
    table_II_baseline_creation,
    table_II_calculation_nowcasting,
    table_III_baseline_creation,
    table_III_calculation_nowcasting,
    translation_columns,
    upload_data,
)


def create_pipeline(**kwargs):
    return Pipeline(
        nodes=[
            node(
                get_most_recent_dataframe,
                inputs="vivalto_data",
                outputs=[
                    "df_number_of_id_vivalto",
                    "df_death_vivalto",
                    "df_critical_health_vivalto",
                ],
                name="get_most_recent_dataframe",
            ),
            node(
                dates_formatting,
                inputs=[
                    "df_number_of_id_vivalto",
                    "df_death_vivalto",
                    "df_critical_health_vivalto",
                ],
                outputs=[
                    "df_number_of_id_vivalto_dates",
                    "df_death_vivalto_dates",
                    "df_critical_health_vivalto_dates",
                ],
                name="dates_formatting",
            ),
            node(
                extract_columns,
                inputs=[
                    "df_number_of_id_vivalto_dates",
                    "df_death_vivalto_dates",
                    "df_critical_health_vivalto_dates",
                ],
                outputs=[
                    "df_number_of_id_columns",
                    "df_death_columns",
                    "df_critical_health_columns",
                ],
                name="extract_columns",
            ),
            node(
                translation_columns,
                inputs=[
                    "df_number_of_id_columns",
                    "df_death_columns",
                    "df_critical_health_columns",
                ],
                outputs=[
                    "df_number_of_id_vivalto_translate",
                    "df_death_vivalto_translate",
                    "df_critical_health_vivalto_translate",
                ],
                name="translation_columns",
            ),
            node(
                missing_data_prepro_I,
                inputs="df_number_of_id_vivalto_translate",
                outputs="table_I_missing_data",
                name="missing_data_prepro_I_node",
            ),
            node(
                missing_data_prepro_II,
                inputs="df_death_vivalto_translate",
                outputs="table_II_missing_data",
                name="missing_data_prepro_II_node",
            ),
            node(
                missing_data_prepro_III,
                inputs="df_critical_health_vivalto_translate",
                outputs="table_III_missing_data",
                name="missing_data_prepro_III_node",
            ),
            node(
                table_I_baseline_creation,
                inputs="table_I_missing_data",
                outputs="table_I_baseline",
                name="table_I_baseline_creation",
            ),
            node(
                table_II_baseline_creation,
                inputs="table_II_missing_data",
                outputs="table_II_baseline",
                name="table_II_baseline_creation",
            ),
            node(
                table_III_baseline_creation,
                inputs="table_III_missing_data",
                outputs="table_III_baseline",
                name="table_III_baseline_creation",
            ),
            node(
                table_I_calculation_nowcasting,
                inputs="table_I_baseline",
                outputs="table_I_nowcasting",
                name="table_I_calculation_nowcasting_node",
            ),
            node(
                table_II_calculation_nowcasting,
                inputs="table_II_baseline",
                outputs="table_II_nowcasting",
                name="table_II_calculation_nowcasting_node",
            ),
            node(
                table_III_calculation_nowcasting,
                inputs="table_III_baseline",
                outputs="table_III_nowcasting",
                name="table_III_calculation_nowcasting_node",
            ),
            node(
                smooth_n_cases,
                inputs="table_I_nowcasting",
                outputs="table_I_final_vivalto",
                name="table_I_smoothing_node",
            ),
            node(
                smooth_n_death,
                inputs="table_II_nowcasting",
                outputs="table_II_final_vivalto",
                name="table_II_smoothing_node",
            ),
            node(
                smooth_n_critical,
                inputs="table_III_nowcasting",
                outputs="table_III_final_vivalto",
                name="table_III_smoothing_node",
            ),
            node(
                upload_data,
                inputs="table_I_final_vivalto",
                outputs="table_I_final_vivalto.local",
                name="table_I_local_smoothing_node",
            ),
            node(
                upload_data,
                inputs="table_II_final_vivalto",
                outputs="table_II_final_vivalto.local",
                name="table_II_local_smoothing_node",
            ),
            node(
                upload_data,
                inputs="table_III_final_vivalto",
                outputs="table_III_final_vivalto.local",
                name="table_III_local_smoothing_node",
            ),
        ]
    )
