# src/data_project/pipeline.py
from kedro.pipeline import Pipeline, node

from .nodes import (
    concatenate_data,
    create_alerts,
    download_data,
    preprocessing,
    upload_data,
)


def create_pipeline(**kwargs):
    return Pipeline(
        nodes=[
            node(
                download_data,
                inputs="pharmacy_data_germany.source",
                outputs="pharmacy_data_germany.extract",
                name="download_pharma_data_node",
            ),
            node(
                download_data,
                inputs="pharmacy_data_germany_all_sales.source",
                outputs="pharmacy_data_germany_all_sales.extract",
                name="download_pharma_data_all_sales_node",
            ),
            node(
                download_data,
                inputs="diagnoses_cgm_past.source",
                outputs="diagnoses_cgm_past.extract",
                name="download_past_diagnoses_node",
            ),
            node(
                download_data,
                inputs="diagnoses_cgm_latest_weeks.source",
                outputs="diagnoses_cgm_latest_weeks.extract",
                name="download_latest_weeks_diagnoses_node",
            ),
            node(
                concatenate_data,
                inputs=["diagnoses_cgm_past.extract","diagnoses_cgm_latest_weeks.extract"],
                outputs="diagnoses_cgm.extract",
                name="concatenate_diagnoses_node",
            ),
            node(
                download_data,
                inputs="prescriptions_cgm_past.source",
                outputs="prescriptions_cgm_past.extract",
                name="download_past_prescriptions_node",
            ),
            node(
                download_data,
                inputs="prescriptions_cgm_latest_weeks.source",
                outputs="prescriptions_cgm_latest_weeks.extract",
                name="download_latest_weeks_prescriptions_node",
            ),
            node(
                concatenate_data,
                inputs=["prescriptions_cgm_past.extract","prescriptions_cgm_latest_weeks.extract"],
                outputs="prescriptions_cgm.extract",
                name="prescriptions_diagnoses_node",
            ),
            node(
                preprocessing,
                inputs=[
                    "diagnoses_cgm.extract",
                    "prescriptions_cgm.extract",
                    "pharmacy_data_germany.extract",
                    "pharmacy_data_germany_all_sales.extract",
                ],
                outputs=[
                    "German_GP_Diagnoses",
                    "German_GP_Diagnoses_rel",
                    "German_GP_Diagnoses_ratio_all",
                    "German_GP_Diagnoses_count_all",
                    "German_GP_Diagnoses_counts_for_trends",
                    "German_Pharmacy_Sales",
                    "German_Pharmacy_Sales_rel",
                    "German_Pharmacy_Sales_ratio_all",
                    "German_Pharmacy_Sales_count_all",
                    "German_GP_Prescriptions",
                    "German_GP_Prescriptions_rel",
                    "German_GP_Prescriptions_ratio_all",
                    "German_GP_Prescriptions_count_all",
                    "German_GP_Prescriptions_counts_for_trends",
                ],
                name="preprocessing_node",
            ),
            node(
                create_alerts,
                inputs=["German_GP_Diagnoses", "German_GP_Diagnoses_rel", "German_GP_Diagnoses_ratio_all", "params:diag_cols_aggr"],
                outputs=["German_GP_Diagnoses_alerts_quinten", "German_GP_Diagnoses_rel_alerts_quinten", "German_GP_Diagnoses_ratio_all_alerts_quinten"],
                name="German_GP_Diagnoses_quinten_alerts_node",
            ),
            node(
                create_alerts,
                inputs=["German_GP_Prescriptions", "German_GP_Prescriptions_rel", "German_GP_Prescriptions_ratio_all", "params:presc_cols_aggr"],
                outputs=["German_GP_Prescriptions_alerts_quinten", "German_GP_Prescriptions_rel_alerts_quinten", "German_GP_Prescriptions_ratio_all_alerts_quinten"],
                name="German_GP_Prescriptions_quinten_alerts_node",
            ),
            node(
                create_alerts,
                inputs=["German_Pharmacy_Sales", "German_Pharmacy_Sales_rel", "German_Pharmacy_Sales_ratio_all", "params:pharm_cols_aggr"],
                outputs=["German_Pharmacy_Sales_alerts_quinten", "German_Pharmacy_Sales_rel_alerts_quinten", "German_Pharmacy_Sales_ratio_all_alerts_quinten"],
                name="German_Pharmacy_Sales_quinten_alerts_node",
            ),
            node(
                upload_data,
                inputs="German_GP_Diagnoses",
                outputs="processed_German_GP_Diagnoses_MongoDB",
                name="diagnoses_MongoDB_node",
            ),
            node(
                upload_data,
                inputs="German_Pharmacy_Sales",
                outputs="processed_German_Pharmacy_Sales_MongoDB",
                name="pharmacy_MongoDB_node",
            ),
            node(
                upload_data,
                inputs="German_GP_Prescriptions",
                outputs="processed_German_GP_Prescriptions_MongoDB",
                name="prescriptions_MongoDB_node",
            ),
            node(
                upload_data,
                inputs="German_GP_Diagnoses_rel",
                outputs="processed_German_GP_Diagnoses_rel_MongoDB",
                name="diagnoses_rel_MongoDB_node",
            ),
            node(
                upload_data,
                inputs="German_Pharmacy_Sales_rel",
                outputs="processed_German_Pharmacy_Sales_rel_MongoDB",
                name="pharmacy_rel_MongoDB_node",
            ),
            node(
                upload_data,
                inputs="German_GP_Prescriptions_rel",
                outputs="processed_German_GP_Prescriptions_rel_MongoDB",
                name="prescriptions_rel_MongoDB_node",
            ),
            node(
                upload_data,
                inputs="German_GP_Diagnoses_ratio_all",
                outputs="processed_German_GP_Diagnoses_ratio_all_MongoDB",
                name="diagnoses_ratio_all_MongoDB_node",
            ),
            node(
                upload_data,
                inputs="German_GP_Prescriptions_ratio_all",
                outputs="processed_German_GP_Prescriptions_ratio_all_MongoDB",
                name="prescriptions_ratio_all_MongoDB_node",
            ),
            node(
                upload_data,
                inputs="German_Pharmacy_Sales_ratio_all",
                outputs="processed_German_Pharmacy_Sales_ratio_all_MongoDB",
                name="pharmacy_sales_ratio_all_MongoDB_node",
            ),
            node(
                upload_data,
                inputs="German_GP_Diagnoses_count_all",
                outputs="processed_German_GP_Diagnoses_count_all_MongoDB",
                name="diagnoses_count_all_MongoDB_node",
            ),
            node(
                upload_data,
                inputs="German_GP_Prescriptions_count_all",
                outputs="processed_German_GP_Prescriptions_count_all_MongoDB",
                name="prescriptions_count_all_MongoDB_node",
            ),
            node(
                upload_data,
                inputs="German_Pharmacy_Sales_count_all",
                outputs="processed_German_Pharmacy_Sales_count_all_MongoDB",
                name="pharmacy_sales_count_all_MongoDB_node",
            ),
            node(
                upload_data,
                inputs="German_GP_Diagnoses_alerts_quinten",
                outputs="German_GP_Diagnoses_alerts_quinten_MongoDB",
                name="upload_German_GP_Diagnoses_alerts_quinten_MongoDB_node",
            ),
            node(
                upload_data,
                inputs="German_GP_Prescriptions_alerts_quinten",
                outputs="German_GP_Prescriptions_alerts_quinten_MongoDB",
                name="upload_German_GP_Prescriptions_alerts_quinten_MongoDB_node",
            ),
            node(
                upload_data,
                inputs="German_Pharmacy_Sales_alerts_quinten",
                outputs="German_Pharmacy_Sales_alerts_quinten_MongoDB",
                name="upload_German_Pharmacy_Sales_alerts_quinten_MongoDB_node",
            ),
            node(
                upload_data,
                inputs="German_GP_Diagnoses_rel_alerts_quinten",
                outputs="German_GP_Diagnoses_rel_alerts_quinten_MongoDB",
                name="upload_German_GP_Diagnoses_rel_alerts_quinten_MongoDB_node",
            ),
            node(
                upload_data,
                inputs="German_GP_Prescriptions_rel_alerts_quinten",
                outputs="German_GP_Prescriptions_rel_alerts_quinten_MongoDB",
                name="upload_German_GP_Prescriptions_rel_alerts_quinten_MongoDB_node",
            ),
            node(
                upload_data,
                inputs="German_Pharmacy_Sales_rel_alerts_quinten",
                outputs="German_Pharmacy_Sales_rel_alerts_quinten_MongoDB",
                name="upload_German_Pharmacy_Sales_rel_alerts_quinten_MongoDB_node",
            ),
            node(
                upload_data,
                inputs="German_GP_Diagnoses_ratio_all_alerts_quinten",
                outputs="German_GP_Diagnoses_ratio_all_alerts_quinten_MongoDB",
                name="upload_German_GP_Diagnoses_ratio_all_alerts_quinten_MongoDB_node",
            ),
            node(
                upload_data,
                inputs="German_GP_Prescriptions_ratio_all_alerts_quinten",
                outputs="German_GP_Prescriptions_ratio_all_alerts_quinten_MongoDB",
                name="upload_German_GP_Prescriptions_ratio_all_alerts_quinten_MongoDB_node",
            ),
            node(
                upload_data,
                inputs="German_Pharmacy_Sales_ratio_all_alerts_quinten",
                outputs="German_Pharmacy_Sales_ratio_all_alerts_quinten_MongoDB",
                name="upload_German_Pharmacy_Sales_ratio_all_alerts_quinten_MongoDB_node",
            ),
        ]
    )
